apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: online-games-pg
  namespace: online-games
spec:
  instances: 1
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: online_games
      owner: app
