apiVersion: v1
kind: Service
metadata:
  name: {{ include "online-games.fullname" . }}-backend
  labels:
    {{- include "online-games.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    {{- include "online-games.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
