apiVersion: v1
kind: Secret
metadata:
  name: {{ include "online-games.fullname" . }}-backend-secrets
  labels:
    {{- include "online-games.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
